//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DINextRun
    {
        public int DINextRunID { get; set; }
        public int DIObjectID { get; set; }
        public string Parameters { get; set; }
        public Nullable<System.DateTime> RunStart { get; set; }
        public Nullable<System.DateTime> RunComplete { get; set; }
        public string Status { get; set; }
        public short ManualRun { get; set; }
    
        public virtual DIObject DIObject { get; set; }
    }
}
