//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobRID { get; set; }
        public int RevJobRID { get; set; }
        public int HomeRID { get; set; }
        public int LotRID { get; set; }
        public int CommunityRID { get; set; }
        public int ModelRID { get; set; }
        public int SlsOrdRID { get; set; }
        public int CustomerRID { get; set; }
        public int SpecLevelRID { get; set; }
        public string Type { get; set; }
        public string JobID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public int SeqNumber { get; set; }
        public string DCStatus { get; set; }
        public System.DateTime DCCompleteDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EstComplDate { get; set; }
        public System.DateTime ComplDate { get; set; }
        public string DataProcStatus { get; set; }
        public string RevisionStatus { get; set; }
        public string RevisionComments { get; set; }
        public string PrevStatus { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int JobPhaseRID { get; set; }
        public string AccProjectID { get; set; }
        public string AccSubAccount { get; set; }
        public int CountPrepaids { get; set; }
        public int CountOpenPrepaids { get; set; }
        public decimal CostOpenAtClosing { get; set; }
        public decimal CostSwept { get; set; }
        public string ScheduleIsPublic { get; set; }
        public int MasterJobRID { get; set; }
        public string NewPOAllowed { get; set; }
        public string NewVPOAllowed { get; set; }
        public string NewInvAllowed { get; set; }
        public string NewBCAllowed { get; set; }
        public string UseSchedule { get; set; }
        public string UsePOs { get; set; }
        public string UseVPOs { get; set; }
        public string UseInvoices { get; set; }
        public string UseJobCost { get; set; }
        public int BankVndRID { get; set; }
        public string SlsOrdStatus { get; set; }
        public decimal BldgCostMultiplier { get; set; }
        public int LDUnitRID { get; set; }
        public int LDProjRID { get; set; }
        public System.DateTime LastRevisedDate { get; set; }
        public System.DateTime CostDate { get; set; }
        public string UseActFromAcc { get; set; }
        public System.DateTime LastSTJobCstStart { get; set; }
        public System.DateTime LastSTJobCstFinish { get; set; }
    }
}
