//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        public int LotRID { get; set; }
        public int CommunityRID { get; set; }
        public int SectionRID { get; set; }
        public int PhaseRID { get; set; }
        public int BuildingRID { get; set; }
        public string FilingNumber { get; set; }
        public string BlockNumber { get; set; }
        public int LotNumber { get; set; }
        public string Type { get; set; }
        public string LotID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Handing { get; set; }
        public string Foundation { get; set; }
        public string Garage { get; set; }
        public string Grade { get; set; }
        public string LotSize { get; set; }
        public decimal LotPremium { get; set; }
        public string SlsWshID { get; set; }
        public int SlsWshIndex { get; set; }
        public string SlsOrdID { get; set; }
        public int SlsOrdIndex { get; set; }
        public string HomeID { get; set; }
        public int HomeIndex { get; set; }
        public string JobID { get; set; }
        public int JobIndex { get; set; }
        public int DefSeqNumber { get; set; }
        public string Status { get; set; }
        public int PendingSlsWshRID { get; set; }
        public string HoldComment { get; set; }
        public string SelectionStatus { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string PlatBookVol { get; set; }
        public string PlatBookPage { get; set; }
        public decimal LotDim1 { get; set; }
        public decimal LotDim2 { get; set; }
        public System.DateTime HoldEndDate { get; set; }
        public string CN_NCB { get; set; }
        public string SellerName { get; set; }
        public System.DateTime AvailableDate { get; set; }
        public System.DateTime EstComplDate { get; set; }
        public string ExternalID { get; set; }
        public string AccProjectID { get; set; }
        public string AccSubAccount { get; set; }
        public decimal LotCost { get; set; }
        public string AccCompanyID { get; set; }
        public string AccJobCompanyID { get; set; }
        public string AccSysStatus { get; set; }
        public string PossessionStatus { get; set; }
        public string DevelopmentStatus { get; set; }
        public int ProfCalcModelRID { get; set; }
        public string SellerNotes { get; set; }
        public int LDParcelRID { get; set; }
    }
}
